<center>
<form name="agregar_ategoria" id="agregar_categoria" method="post" action="">
	<table>
		<tr>
			<td>Nombre: </td>
			<td><input type="text" name="nombre_categoria" class="input-medium search-query" id="nombre"></td>
		</tr>
		<tr align="center">
			<td colspan="2">
				<textarea placeholder="Descripción" name="descripcion_categoria" id="descripcion"></textarea>
			</td>
		</tr>
		<tr align="center">
			<td colspan="2">
				<input type="hidden" value="si" name="grabar">
				<input type="submit" value="Guardar" class="btn btn-primary">
				<button type="reset" class="btn btn-primary">Limpiar</button>
			</td>
		</tr>
	</table>
</form>
</center>