<!DOCTYPE HTML>
<?php
if (isset($_GET['e'])) {
	
	switch ($_GET["e"]) {
		case '1': 
				$error = "Falta algun Valor o Tiene Algun dato Incorrecto";
			break;
		
		default:
				header("location: ".Conectar::ruta()."?accion=error"); 
			break;
	}
}
?>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
	<script>
	  $('.fecha_nac').datepicker()
	</script>
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<section id="contenido_system" style="width:100%;">
		<center><h2>Registrar Alumno</h2></center>
		<hr>
		<div style="width:100%; text-align:left;">
					
					<section class="well">
						

						
			<form name="alumnos" action="" method="post">
				<div class="row">
					<div class="row-fluid span12" style="background:;">
						<div class="span6">
							<fieldset>
								<legend><center><h3>Datos Personales</h3></center></legend>
								<center>
									<table border="0" width="100%">
										<tr>
											<td align="right" width="20%">Cédula:</td>
											<td width="25%">
												<select name="nacionalidad" class="input-medium">
													<option value="0" selected="selected">
														Seleccione...
													</option>
													<option value="V">
														V- Venezolano
													</option>
													<option value="E">
														E- Extranjero
													</option>
												</select>
											</td>
											<td width="10%">
												<input type="text" name="cedula" class="input-small" maxlength="8" placeholder="Ej: 00000000"/>
											</td>
										</tr>
										<tr>
											<td align="right">Nombre: </td>
											<td>
												<input class="input-medium" type="text" name="nombre"/>
											</td>
											<td align="right">Apellido: </td>
											<td>
												<input type="text" class="input-medium" name="apellido"/>
											</td>
										</tr>
										<tr>
											<td align="right">F. Nacimiento: </td>
											<td>
												<input class="input-medium" type="text" id="fecha_nac" name="fecha_nac" value="">
											</td>
											<td align="right">Sexo: </td>
											<td>
												<select name="sexo" class="input-medium">
													<option value="0" selected="selected">
														Seleccione...
													</option>
													<option value="Femenino">
														Femenino
													</option>
													<option value="Masculino">
														Masculino
													</option>
											    </select>
											</td>
										</tr>
										<tr>
											<td align="right">Celular: </td>
											<td>
												<input type="text" name="telf_personal" class="input-medium"/>
											</td>
											<td align="right">Correo: </td>
											<td>
												<input type="text" class="input-medium" name="correo"/>
											</td>
										</tr>
										<tr>
											<td align="right">Profesión: </td>
											<td>
												<select name="profesion" class="input-medium" >
												<option value="0" selected="selected">
													Seleccione
												</option>
													<?php
														for($p = 0; $p < sizeof($profesion); $p++)
														{
														?>
															<option value="<?php echo $profesion[$p]["id_profesion"]; ?>">
																<?php echo $profesion[$p]["nombre_profesion"]; ?>
															</option>		
														<?php	
														}
														?>
												</select>
											</td>
										</tr>
									</table>
								</center>
							</fieldset>
						</div>

						<div class="span6">
							<fieldset>
								<legend><center><h3>Datos Habitación</h3></center></legend>
								<center>
									<table border="0">
										<tr>
											<td>Estado: </td>
											<td>
												<select name="estado" class="input-medium">
												<option value="0" selected="selected">
													Seleccione
												</option>
													<?php
														for($i = 0; $i < sizeof($estado); $i++)
														{
														?>
															<option value="<?php echo $estado[$i]["id_estado"]; ?>">
																<?php echo $estado[$i]["estado"]; ?>
															</option>		
														<?php	
														}
														?>
												</select>
											</td>
											<td>Ciudad: </td>
											<td><input type="text" name="ciudad"/></td>
										</tr>
										<tr>
											<td>Teléfono: </td>
											<td><input type="text" class="input-medium" name="telf_trabajo"/></td>
										</tr>
									</table>
								</center>
								
							</fieldset>
						</div>

					</div>
				</div>
				
				<center>
					<input type="hidden" name="grupo" value="2"/>
					<input type="hidden" name="grabar" value="si"/>
					<tr>
						<?php
							if (isset($_GET["e"])) {
								
								echo "<span class='label label-important'>".$error."</span><br><br>";
							}
						?>
						<td colspan="2" align="center">
							<input class="btn btn-info" type="submit" name="agregar" onClick="agregar_alumno();"/></td>
						<button type="reset" class="btn btn-info">Limpiar</button>
						<a href="?accion=alumnos" class="btn btn-info">Volver</a>
					</tr>
					</table>
				</center>			
			</form>
		</section>

	</div>	
			
			

	</section>


	<footer id="footer_system">
		<?php 
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/funciones.js"></script>
    <script src="<?php echo Conectar::ruta()?>public/js/modernizr.custom.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
</body>
</html>