<!DOCTYPE HTML>
<?
// print_r($_SESSION);
//     exit();
?>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<section id="contenido_system">
		<div style="width=100%">
			<center>
				<h2>Cursos</h2>
			</center>
			<hr>
		</div>
		

		<div class="span12 offset2" style="background:; text-align:left;">
					
					
					<article class="well">
						<a class="btn btn-inverse pull-left" href="?accion=crear_curso1"><i class="icon-plus icon-white"></i>Registrar</a>
						<a class="btn btn-inverse pull-right" href="?accion=reporte_cursos" target="_blank"><i class="icon-folder-open icon-white"></i>Descargar Listado</a>
					</article>
					<article class="well-fluid">
						<table class="table table-striped table-bordered table-condensed">
							<thead>
								<tr>	
									<th>Nombre</th>
									<th>Nivel</th>
									<th>Horario</th>
									<th>Fecha de Inicio</th>
									<th>Fecha de Culminación</th>
									<th>Capacidad</th>
									<th>Profesor</th>
									
									
									<th collspan="3">Acciones</th>
								</tr>
							</thead>
							<tbody>
								<?php
									for($i=0;$i<sizeof($cursos1);$i++)
									{
								?>
									<tr>
										<td><?php echo $cursos1[$i]["nombre"];?> </td>
										<td><?php echo $cursos1[$i]["nivel"];?> </td>
										<td><?php echo $cursos1[$i]["horario"];?></td>
										<td><?php echo $cursos1[$i]["fecha_inicio"];?></td>
										<td><?php echo $cursos1[$i]["fecha_final"];?></td>
										<td><?php echo $cursos1[$i]["capacidad"];?></td>
										<td><?php echo $cursos1[$i]["profesor"];?></td>
																				
										<td>
											<a href="?accion=detalle_cursos1&id=<?php echo $cursos1[$i]['id_curso']?>"><i class="icon-list-alt"></i>Detalles</a><br>
											
											<a href="?accion=editar_curso&id=<?php echo $cursos1[$i]['id_curso']?>"><i class="icon-pencil"></i>Editar</a><br>
											
											
											<a href="javascript:eliminar(<?php echo $cursos1[$i]['id_curso'] ?>, 'eliminar_curso')"><i class="icon-trash"></i>Eliminar</a>
										</td>
									</tr>
							<?php
								}
							?>
							</tbody>
						</table>
						<center>
							<article id="paginador">
								<?php
									if ($inicio > 0) 
									{
										//echo "hola";
										$var=$pagina;
										$var--;
										echo "<a href=".Conectar::url()."&pagina=". $var ."><i class="."icon-chevron-left"."></i></a>";
									}else
									{
										echo "<i class="."icon-chevron-left"."></i>";
									}
									if ($total_paginas > 1)
									 {
										for ($i=1;$i<=$total_paginas;$i++)
										{
											if ($pagina == $i) 
											{
												//si muestro el indice de la pagina actual, no coloco enlace
												echo $pagina . " ";
											}else
											{
												//si el indice no corresponde con la pagina mostrada actualmente, coloco el enlace para ir a esa pagina
												echo "<a href=".Conectar::url()."&pagina=" . $i . "&criterio=" . $txt_criterio . "'>" . $i . "</a>";
											}
										}
									}
									//echo $inicio;
									if ($pagina == $total_paginas)
									 {
										echo "<i class="."icon-chevron-right"."></i>";
									}else
									{
										$var=$pagina;
										$var++;
										echo "<a href=".Conectar::url()."&pagina=". $var . "><i class="."icon-chevron-right"."></i></a>";		
									}
									?>
									<center>
										<?php
											echo "Total Registros Econtrados:(".$total_paginas;
											echo ") || Total Páginas Existentes:(".$total_paginas.")<br>";
									?>
									</center>
							</article>
						</center>
					</article>
				</div>			
			

	</section>


	<footer id="footer_system">
		<?php 
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
    <script src="<?php echo Conectar::ruta()?>public/js/modernizr.custom.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/funciones.js"></script>
</body>
</html>