<!DOCTYPE html>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
    <script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<div style="width=100%">
		<center>
			<h2>Detalles del Curso</h2>
		</center>
		<hr>

		<div class="well" style="background:; text-align:left;">
			<h3><center>
					Curso de: <?php echo $cursos1[0]['nombre'];?><br>
					00/00 	
				</center></h3>
			<br>
			

			<div id="tablas_detalle">
				<center>
				<fieldset>
					<legend><h3>Características</h3></legend>
					<table border="0" width="80%">
						<tr>
							<td align="right" width="28%"><h4>Descripción: </h4></td>
							<td></td><?php echo $cursos1[0]['descripcion'];?></td>
						</tr>
						<tr>
							<td align="right" width="15%"><h4>Fecha de Inicio: </h4></td>
							<td><?php echo $cursos1[0]['fecha_inicio']?></td>
						</tr>
						<tr>
							<td align="right" width="28%"><h4>Fecha de Culminación: </h4></td>
							<td><?php echo $cursos1[0]['fecha_final']?></td>
						</tr>
						<tr>
							<td align="right"><h4>Horario: </h4></td>
							<td><?php echo $cursos1[0]['horario'];?></td>
						</tr>
						<tr>
							<td align="right"><h4>Profesor: </h4></td>
							<td><?php echo $cursos1[0]['profesor']?></td>

						</tr>
					</table>
				</fieldset>
				</div>
			<hr>
			<center>
				<a class="btn btn-inverse" href=""><i class="icon-pencil icon-white"> </i> Editar</a>
				<a class="btn btn-inverse" target="_blank" href="#">Descargar Datos</a>
			</center>

			<section class="offset2 well">
				<a href="#myModal2" role="button" class="btn btn-primary" data-toggle="modal">Asignar</a>
			<br><br><br>
			<h3>Alumno: </h3>
			<br>
			<?php
				for ($i=0; $i < sizeof($alumnos); $i++) { 
					echo "<h4>".$alumnos[$i]["nombre"]."</h4><br>";
				}
			?>
			<hr>
			<table class="span12">
							<thead>
								<tr>	
									<th>Cédula</th>
									<th>Nombre</th>
									<th>Apellido</th>
									<th>Edad</th>
									
								</tr>
							</thead>
							<tbody>
								<?php
									for($i=0;$i<sizeof($alumnos);$i++)
									{
								?>
									<tr>
										<td><?php echo $alumnos[$i]["cedula"];?> </td>
										<td><?php echo $alumnos[$i]["nombre"];?></td>
										<td><?php echo $alumnos[$i]["apellido"];?></td>
										<td>
											<?php
												$anio = $alumnos[$i]["fecha_de_nacimiento"];
												$fecha = substr($anio, 0,4); 
												$anio_a = date("Y");
												echo $edad = $anio_a - $fecha;
											?>
										</td>
										
										
										
									</tr>
							<?php
								}
							?>
							</tbody>
						</table>
			</section>
			
		</div>
	</div>

	<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">Agregar Alumno <?php echo $cursos1[0]['nombre'];?> </h3>
		  </div>
		  <div class="modal-body">
		    <p>
		    <?php
		    	require_once("controller/asignar_alumnoController.php");
		    ?>
		    </p>
		  </div>
		  <div class="modal-footer">
		    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
		  </div>
		</div>


	
	<footer>
		<?php
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script type="text/javascript" src="<?php echo Conectar::ruta()?>public/js/carousel.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta()?>public/js/bootstrap-transition.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta(); ?>public/js/funciones.js"></script>
</body>

</html>