<!DOCTYPE html>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
    <script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<div style="width=100%">
		<center>
			<h2>Detalles del Alumno</h2>
		</center>
		<hr>

		<div class="well" style="background:; text-align:left;">
			<h3><center>
					<?php echo $alumnos[0]['nombre']." ".$alumnos[0]['apellido'];?><br>
					Fecha de Ingreso: <?php echo $alumnos[0]['fecha_ingreso'];?>
				</center></h3>
			<br>
			

			<div id="tablas_detalle">
				<center>
				<fieldset>
					<legend><h3>Datos Personales</h3></legend>
					<table border="0" width="80%">
						<tr>
							<td align="right" width="28%"><h4>Nombre Completo: </h4></td>
							<td width="30%"><?php echo $alumnos[0]['nombre']." ".$alumnos[0]['apellido'];?></td>
							<td align="right" width="10%"><h4>Cédula: </h4></td>
							<td><?php echo $alumnos[0]['nacionalidad']."-".$alumnos[0]['cedula'];?></td>
						</tr>
						<tr>
							
							<td align="right"><h4>Fecha de Nacimiento: <?php $fecha_nueva = Conectar::voltear_fecha($alumnos["0"]['fecha_de_nacimiento']);
								echo $fecha_nueva;
								?>
								</h4></td>
					
							<td align="right"><h4>Sexo: </h4></td>
							<td><?php echo $alumnos[0]['sexo'];?></td>
						</tr>
						<tr>

							<td align="right"><h4>Teléfono Personal: </h4></td>
							<td><?php echo $alumnos[0]['telf_personal'];?></td>
							<td align="right"><h4>Correo: </h4></td>
							<td><?php echo $alumnos[0]['correo'];?></td>
						</tr>
						<tr>
							<td align="right"><h4>Profesión: </h4></td>
							<td><?php echo $alumnos[0]['profesion'];?></td>
						</tr>
					</table>
				</fieldset>

				<br>
				<fieldset>
					<legend><h3>Datos Habitación</h3></legend>
					<table border="0" width="100%">
						<tr>
							<td align="right" width="28%"><h4>Estado: </h4></td>
							<td width="20%"><?php echo $alumnos[0]['estado'];?></td>
							<td align="right" width="16%"><h4>Ciudad: </h4></td>
							<td><?php echo $alumnos[0]['ciudad'];?></td>
						</tr>
						<tr>
							<td align="right"><h4>Municipio: </h4></td>
							<td><?php echo $alumnos[0]['municipio'];?></td>
							<td align="right"><h4>Dirección: </h4></td>
							<td><?php echo $alumnos [0]['direccion'];?></td>
						</tr>
						<tr>
							<td align="right"><h4>Teléfono: </h4></td>
							<td><?php echo $alumnos[0]['telf_trabajo'];?></td>
						</tr>
					</table>
				</fieldset>
				</div>
			<hr>
			<center>
				<a class="btn btn-inverse" href="?accion=editar_alumno&id=<?php echo $alumnos[0]['id_persona']?>"><i class="icon-pencil icon-white"> </i> Editar</a>
				<a class="btn btn-inverse" target="_blank" href="#">Descargar Datos</a>
			</center>

			


		</div>

	</div>

	


	
	<footer>
		<?php
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script type="text/javascript" src="<?php echo Conectar::ruta()?>public/js/carousel.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta()?>public/js/bootstrap-transition.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta(); ?>public/js/funciones.js"></script>
</body>

</html>