<!DOCTYPE HTML>
<?
// print_r($_SESSION);
//     exit();
?>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<section id="contenido_system">
		<center>
			<h2>Facturación</h2>
			<hr>
		</center>
		
		<div class="span12 offset2">
			<article class="well">
				<a href="?accion=nuevaFactura" class="btn btn-primary"><i class="icon-plus icon-white"></i>  Nueva Factura</a>
				<button class="btn btn-primary pull-right"><i class="icon-folder-open icon-white"></i>  Descargar Listado</button>
			</article>

			<article class="well-fluid">
				<div id="facturas">
					<div class="well">
						<table width="100%" border="0">
							<tr>
								<td align="center"><b>Fecha</b></td>
								<td align="center"><b>Nombre Cliente</b></td>
								<td align="right"><b>Monto</b></td>
								<td align="center"><b>Estado de Factura</b></td>
							</tr>
						</table>
					</div>
					<?php for ($i=0; $i<sizeof($facturas) ; $i++) { 
						$fecha_nueva = Conectar::voltear_fecha($facturas[$i]['fecha']);
					?>
					<div class="well">
						<table width="100%" border="0">
							<tr>
								<td width="14%" align="center"><?php echo $fecha_nueva;?></td>
								<td width="34%" align="center"><?php echo $facturas[$i]["nombreCliente"];?></td>
								<td width="13%" align="right"><?php echo $facturas[$i]["monto_total"];?></td>
								<td align="center"><?php echo $facturas[$i]["estadoFactura"];?></td>
							</tr>
						</table>
					</div>
					<?php
					}
					?>
				</div>
				<article id="paginador">
							<center>
								<?php
									if ($inicio > 0) 
									{
										//echo "hola";
										$var=$pagina;
										$var--;
										echo "<a href=".Conectar::url()."&pagina=". $var ."><img src="."public/img/icon/Left.png"."></a>";
									}else
									{
										// echo "<i class="."icon-chevron-left"."></i>";
										echo "<img src="."public/img/icon/Left.png".">";
									}
									if ($total_paginas > 1)
									 {
										for ($i=1;$i<=$total_paginas;$i++)
										{
											if ($pagina == $i) 
											{
												//si muestro el indice de la pagina actual, no coloco enlace
												echo $pagina . " ";
											}else
											{
												//si el indice no corresponde con la pagina mostrada actualmente, coloco el enlace para ir a esa pagina
												echo "<a href=".Conectar::url()."&pagina=" . $i . "&criterio=" . $txt_criterio . "'>" . $i . "</a>";
											}
										}
									}
									//echo $inicio;
									if ($pagina == $total_paginas)
									 {
										// echo "<i class="."icon-chevron-right"."></i>";
										echo "<img src="."public/img/icon/Right.png".">";
									}else
									{
										$var=$pagina;
										$var++;
										echo "<a href=".Conectar::url()."&pagina=". $var . "><img src="."public/img/icon/Right.png"."></a>";		
									}
									?>
									
										<?php
											echo "Total Registros Econtrados:(".$total_paginas;
											echo ") || Total Páginas Existentes:(".$total_paginas.")<br>";
									?>
									</center>
							</article>
			</article>
		</div>
			

	</section>


	<footer id="footer_system">
		<?php 
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
    <script src="<?php echo Conectar::ruta()?>public/js/modernizr.custom.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
</body>
</html>