<div class="">

	<div id="footer" class="span12 offset2">

		<div class="row-fluid">
			<div class="span4 offset2">
				<div style="margin-left:190px; margin-top:0px; background:;">
					<ul class="unstyled">
						<li>FAQs</li>
						<li>Contacta</li>
						<li>Acerca de</li>
					</ul>
				</div>
			</div>

			<div class="span3" style="margin-left:150px; margin-top:0px; background:;">
				<ul class="unstyled">
					<li>Cursos</li>
					<li>Servicio Técnico</li>
					<li>Redes</li>
					<li>Desarrollo</li>
				</ul>
			</div>

			<div class="span2" style="margin-top:0px; margin-left:35px; background:;">
				<p>Encuentranos</p>
				<img src="public/img/32px/facebook.png">
				<img src="public/img/32px/twitter.png">
			</div>
		</div>

		<div id="footer_contenido">
			<div class="span6">
				<center>
					<p>Alvaro Telecomunicaciones 2013 | &copy;Todos los Derechos Reservados.</p>

					<p>Web Desarrollada Por: Miguel Torrealba y Keiberth Padrón.</p>
				</center>
			</div>
			
		</div>
	</div>

</div>
