<div id="header_sys" class="" style="">
	
	<div id="logoh_sys" class="span1">
		<img src="public/img/logo_opt.png">
	</div>

	<div id="letrash_sys" class="span10" style="background:;">
		<p align="center">Alvaro Telecomunicaciones<br>
		"SATEL" Sistema Administrativo Compañía ATEL</p>
	</div>

	<div id="fechah_sys" class="span2" style="background:;">
		Fecha: <?php 
				echo date ("d-m-Y");
			  ?> 
	</div>

	<!-- <div id="horah_sys" class="span3 " style="background:;">
		Hora: <?php
				echo date("h:i:s");
			 ?>
	</div> -->
</div>