<!DOCTYPE HTML>
<?
// print_r($_SESSION);
//     exit();
?>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
	
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<section id="contenido_system">
		<div  style="background:; width=100%;">
			
			
				<div class="row-fluid" >
					<div style="position: absolute; float: left; left:80px; ">
						<h3>Bienvenido <?php if($_SESSION['usuario_lvl'] == '1') {
							?>	
								Administrador: 
							<?php
							}else{
								if ($_SESSION['usuario_lvl'] == '2') {
							?>
								Profesor: 
							<?php
								}else{
									if ($_SESSION['usuario_lvl'] == '3') {
									?>
									Estudiante: 
									<?php
									}
								}
							}
							?>
						 <a href="#"><?php echo $_SESSION['usuario_nom'];?></a>	
						</h3>
					</div>
					
					
					<!-- <div style="position: fixed; float: right; right:40px; top:20%;">
						<form class="form-search">
						  <input type="text" class="input-medium search-query">
						  <button type="submit" class="btn">Buscar</button>
						</form>
					</div> -->
						
					

				</div>
			
		</div>


		<div style="width:100%;">
			<br><br>	
			<hr>
		</div>
				
		<div class="span7 offset1" style="background:;">
			<div class="well">
				<center><h3>Accesos Rápido</h3></center><br>
				<div class="row-fluid">
					<div class="span6" style="font-weight:bold; font-size:14px;">
						<img src="public/img/icon/Inbox.png"><a href="?accion=#myModal" role="button" data-toggle="modal">Revisar Pre-Inscritos</a><br><br>
						<img src="public/img/icon/Wallet-Money.png"><a href="#">Revisar Pagos</a><br><br>
					</div>
					<div class="span6" style="font-weight:bold; font-size:14px;">
						<img src="public/img/icon/Clipboard.png"><a href="#">Generar Listado</a><br><br>
						<img src="public/img/icon/Status.png"><a href="#">Revisar Estadísticas</a><br><br>
					</div>
				</div>
			</div>
		</div>

		<div class="span7 offset1" style="background:;">
			<div class="well">
				<center><h3>Noticias</h3></center><br>
				<div class="row-fluid">
					<div class="span4" style="font-weight:bold; font-size:14px;">
						<a href="?accion=#myModalnot" role="button" data-toggle="modal">Agregar Noticia</a><br><br>
					</div>
					<div class="span4" style="font-weight:bold; font-size:14px;">
						<a href="#">Visualizar Noticias</a><br><br>
					</div>
					<div class="span4" style="font-weight:bold; font-size:14px;">
						<a href="#">Panel de Noticias</a>
					</div>
				</div>
			</div>
		</div>

	</section>

	<!-- Modal Pre-Inscritos -->
	<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header" style="background:#262626; color:#f2f2f2;">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">Personas Pre-Inscritas</h3>
		</div>

	 	<div class="modal-body">
		    <p>
		    	<?php
		    		require_once("controller/lista_pre_inscritosController.php");
		    	?>
		    </p>
	  	</div>

	  	<div class="modal-footer" style="background:#262626;">
	    	<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cerrar</button>
	  	</div>
	</div>
	<!-- Fin Modal Pre-Inscritos -->

	<!-- Modal Agregar Noticia -->
	<div id="myModalnot" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header" style="background:#262626; color:#f2f2f2;">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">Agregar Noticia</h3>
		</div>

	 	<div class="modal-body">
		    <p>
		    	<?php
		    		require_once("controller/agregar_noticiaController.php");
		    	?>
		    </p>
	  	</div>

	  	<div class="modal-footer" style="background:#262626;">
	    	<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cerrar</button>
	  	</div>
	</div>
	<!-- Fin Modal Agregar Noticia -->

	<footer id="footer_system">
		<?php 
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
    <script src="<?php echo Conectar::ruta()?>public/js/modernizr.custom.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
</body>
</html>