<div id="menu">
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<!-- <div class="brand">
				<a href="?accion=#">Menú</a>
			</div> -->
			<ul class="nav">
				<li class="divider-vertical"></li>
				<li class="active">
					<a href="?accion=index">Inicio</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=somos">¿Quiénes Somos?</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=cursos">Cursos</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=redes">Redes</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=servicios">Servicio Técnico</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=desarrollo">Desarrollo</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="?accion=contacto">Contacto</a>
				</li>
				<li class="divider-vertical"></li>
				<li>
					<a href="">Fecha: <? echo date('d-m-Y'); ?></a>
				</li>
				<li class="divider-vertical"></li>
			</ul>
		</div>
	</div>
</div>
</div>