<form method="post" name="new_user" action="" class="form-inline">
	<center>
	<table>
		<tr>
			<td>Usuario:</td><td><input type="text" name="login" placeholder="Admite letras y números" class="input-medium"></td>
		</tr>
		<tr>
			<td>Clave:</td><td><input type="password" name="pass" placeholder="*******" class="input-medium"></td>
		</tr>
		<tr align="center">
			<td colspan="2">
				<input type="hidden" name="nivel" value="3">
				<input type="hidden" name="agregar_usuario" value="grabar">
				<input type="submit" name="enviar" value="Crear" class="btn btn-primary">
			</td>
		</tr>
	</table>
	</center>
</form>