<form name="nuevo_cliente" method="post" action="" id="nuevo_cliente">
	<table>
		<tr>
			<td><input type="text" name="cedula" class="input-medium" placeholder="Cédula"></td>
			<td><input type="text" name="nombre" class="input-large" placeholder="Nombres"></td>
		</tr>
		<tr>
			<td><input type="text" name="apellido" class="input-large" placeholder="Apellidos"></td>
			<td><input type="text" name="telefono" class="input-medium" placeholder="Telefono"></td>
		</tr>
		<tr align="right">
			<td><input type="text" name="correo" class="input-large" placeholder="Correo Electrónico"></td>
			<td><input type="text" name="direccion" class="input-large" placeholder="Dirección"></td>
		</tr>
		<tr align="center">
			<td colspan="2">
				<input type="hidden" name="nuevo" value="si">
				<input type="submit" name="Registrar" class="btn btn-primary">
				<button type="reset" class="btn btn-primary">Cancelar</button>
			</td>
		</tr>
	</table>
</form>