<!DOCTYPE HTML>
<?
// print_r($_SESSION);
//     exit();
?>
<html lang="es">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="icon" type="image/png" href="public/img/favicon.png" />
	<title>.::ATEL~Telecomunicaciones::..</title>
	<!--Aqui van Mis Archivos CSS-->
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap-responsive.css">
	<link rel="stylesheet" type="text/css" href="public/css/bootstrap.css">
</head>

<body>
	<header>
		<?php
			require_once('views/header_system.phtml');
		?>
	</header>

	<div id="menu_sys">
		<?php
			require_once('views/menu_system.phtml');
		?>
	</div>

	<section id="contenido_system">
		<center>
			<h2>Factura<br></h2><h3>Cargo de Productos</h3>
			<hr>
			<article class="span12 offset2 well">
				<div class="row-fluid">
					<div class="span5 offset 2 well pull-left">
						<h3>Datos</h3>

						<h4>Cliente: <?php echo $datos[0]["nombreCliente"]." ".$datos[0]["apellido"];?>
							Cédula: <?php echo  $datos[0]["cedula"];?>
						</h4>

					</div>
					
					<div class="span5 well">
						<h4>Fecha: <?php $fecha_nueva = Conectar::voltear_fecha($datos["0"]['fecha']);
							echo $fecha_nueva; ?><br>
							Vendedor: <?php echo $datos[0]["login"]?></h4>
					</div>

					<div class="span10 well form-horizontal">
						<div class="pull-right">
							<a href="?accion=#myModal" class="btn btn-primary" role="button" data-toggle="modal">Agregar</a>
						</div>
						<center><h3>Productos</h3></center>
						<table class="table table-striped table-bordered table-condensed">
							<thead>
								<tr>
									<th>Cantidad</th>
									<th>Descripción</th>
									<th>Precio Unitario</th>
									<th>Total</th>
									<th colspan="2">Acciones </th>
								</tr>
							</thead>
							<tbody>
								<?php for ($i=0; $i<sizeof($productos); $i++) 
								{
								?>
								<tr>
									<th><?php echo $productos[$i]["cantidad_producto"];?></th>
									<th><?php echo $productos[$i]["nombre_producto"];?></th>
									<th><?php echo $productos[$i]["pvp"];?></th>
									<th><?php 

										$cantidad = $productos[$i]["cantidad_producto"];
										$pvp = $productos[$i]["pvp"];
										$multiplicacion = $cantidad*$pvp;
										echo $multiplicacion;
										$total = $multiplicacion;

										// $sumatoria = $multiplicacion[$i]+=$multiplicacion;

										?>
									</th>
								
									<th><a href="?accion=#">Quitar</a></th>
								</tr>
								<?php
								} 
								?>

							</tbody>

							<tr align="right">
								<td colspan="3"></td>
								<td><b>Monto Total</b></td>
							</tr>
							<tr align="right">
								<td colspan="3"></td>
								<td></td>
							</tr>
						</table>
						<div>
						</div>
					</div>
				</div>
			</article>
			
		</center>
	</section>

	<!-- Modal agregar producto -->
	<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header" style="background:#262626; color:#f2f2f2;">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">Agregar Producto</h3>
		</div>

	 	<div class="modal-body">
		    <p>
		    	<?php
		    		require_once("controller/addProductoController.php");
		    	?>
		    </p>
	  	</div>

	  	<div class="modal-footer" style="background:#262626;">
	    	<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cerrar</button>
	  	</div>
	</div>
	<!-- Fin Modal Agregar producto -->

	<footer id="footer_system">
		<?php 
			require_once('views/footer_system.phtml');
		?>
	</footer>

	<script src="<?php echo Conectar::ruta()?>public/js/jquery.js"></script>
    <script src="<?php echo Conectar::ruta()?>public/js/modernizr.custom.js"></script>
	<script src="<?php echo Conectar::ruta()?>public/js/bootstrap.js"></script>
</body>
</html>